"use client";
import { useEffect, useRef, useState } from "react";
import "leaflet/dist/leaflet.css";
import { Button } from "@/components/ui/Button";
import { Field } from "@/components/ui/Field";
import { useI18n } from "@/lib/i18n";
export interface Coords { latitude: number; longitude: number; }
const MAX_DISTANCE_KM = 25;
function distanceKm(a: Coords, b: Coords) { const r = 6371; const lat = (b.latitude - a.latitude) * Math.PI / 180; const lon = (b.longitude - a.longitude) * Math.PI / 180; const x = Math.sin(lat / 2) ** 2 + Math.cos(a.latitude * Math.PI / 180) * Math.cos(b.latitude * Math.PI / 180) * Math.sin(lon / 2) ** 2; return r * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }
export function LocationCapture({ onChange }: { onChange: (coords: Coords | null) => void }) {
  const { t } = useI18n(); const mapRef = useRef<HTMLDivElement>(null); const leafletRef = useRef<{ map: import("leaflet").Map; marker?: import("leaflet").Marker } | null>(null);
  const [origin, setOrigin] = useState<Coords | null>(null); const [grievance, setGrievance] = useState<Coords | null>(null); const [state, setState] = useState<"idle" | "busy" | "done" | "denied">("idle"); const [mapOpen, setMapOpen] = useState(false); const [mapError, setMapError] = useState<string | null>(null);
  function capture() { if (!navigator.geolocation) { setState("denied"); return; } setState("busy"); navigator.geolocation.getCurrentPosition((pos) => { const next = { latitude: pos.coords.latitude, longitude: pos.coords.longitude }; setOrigin(next); setState("done"); onChange(grievance ?? next); }, () => { setState("denied"); onChange(null); }); }
  useEffect(() => { if (!mapOpen || !origin || !mapRef.current || leafletRef.current) return; let cancelled = false; let invalidateTimer: ReturnType<typeof setTimeout> | undefined; void import("leaflet").then(({ default: L }) => { if (cancelled || !mapRef.current) return; const map = L.map(mapRef.current, { zoomControl: true }).setView([origin.latitude, origin.longitude], 15); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "© OpenStreetMap" }).addTo(map); L.marker([origin.latitude, origin.longitude]).addTo(map).bindPopup(t("locPopupOrigin")).openPopup(); const pinIcon = L.divIcon({ className: "", html: '<span style="display:block;width:22px;height:22px;border-radius:50% 50% 50% 0;background:#ff6b00;border:3px solid #fff;box-shadow:0 1px 5px rgba(0,0,0,.35);transform:rotate(-45deg)"></span>', iconSize: [22, 22], iconAnchor: [11, 20] }); const select = (lat: number, lon: number) => { if (cancelled) return; const picked = { latitude: lat, longitude: lon }; if (distanceKm(origin, picked) > MAX_DISTANCE_KM) { setMapError(t("locOutOfRange", { km: MAX_DISTANCE_KM })); return; } setMapError(null); setGrievance(picked); onChange(picked); if (leafletRef.current?.marker) leafletRef.current.marker.remove(); const marker = L.marker([lat, lon], { icon: pinIcon, draggable: true }).addTo(map).bindPopup(t("locPopupDrag")).openPopup(); marker.on("dragend", () => { const point = marker.getLatLng(); select(point.lat, point.lng); }); leafletRef.current = { map, marker }; }; map.on("click", (event) => select(event.latlng.lat, event.latlng.lng)); leafletRef.current = { map }; invalidateTimer = setTimeout(() => { if (cancelled) return; try { map.invalidateSize(); } catch { /* map already destroyed */ } }, 100); }); return () => { cancelled = true; if (invalidateTimer) clearTimeout(invalidateTimer); leafletRef.current?.map.remove(); leafletRef.current = null; }; }, [mapOpen, origin, onChange]); // eslint-disable-line react-hooks/exhaustive-deps -- `t` intentionally omitted: the map and its popups are created once on open; reopen the map after a language switch.
  return <Field label={t("incidentLocation")} required hint={t("locHint")}><div className="space-y-2"><Button type="button" variant={origin ? "outline" : "secondary"} size="md" onClick={capture} disabled={state === "busy"} className="h-10 w-full justify-start text-xs font-medium">{state === "busy" ? t("locBusy") : origin ? t("locCaptured") : t("locPin")}</Button><Button type="button" variant="secondary" size="md" onClick={() => { if (origin) { setMapOpen((value) => !value); setMapError(null); } }} disabled={!origin} className="h-10 w-full justify-start text-xs font-medium">{mapOpen ? t("locCloseMap") : t("locChooseMap")}</Button>{origin && <>{mapOpen && <div className="overflow-hidden rounded-md border border-ink-200"><div ref={mapRef} className="h-64 w-full cursor-crosshair" role="application" aria-label="Choose grievance location map" /><div className="flex items-center justify-between gap-3 border-t border-ink-100 bg-ink-50 px-3 py-2 text-[11px] text-ink-500"><span>{t("locClickMap")}</span><span>{t("locDragPin")}</span></div></div>}{mapError && <p className="text-[11px] font-medium text-rose-600">{mapError}</p>}<p className="text-[11px] font-medium text-emerald-600">{grievance ? t("locExact", { coords: `${grievance.latitude.toFixed(5)}, ${grievance.longitude.toFixed(5)}` }) : t("locNotSelected")}</p></>}{!origin && <p className="text-[11px] text-ink-400">{t("locCaptureFirst")}</p>}{state === "denied" && <span className="block text-[11px] text-rose-500">{t("locDenied")}</span>}</div></Field>;
}
