"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { acceptAssignment, addProgressUpdate, escalateGrievance, getGrievanceHistory, listGrievances, submitResolution, transitionGrievanceState } from "@/lib/api";
import type { Grievance } from "@/lib/types";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Field, Input, Select, Textarea } from "@/components/ui/Field";
import { StatusBadge, PriorityBadge } from "@/components/ui/Badge";
import { useToast } from "@/components/ui/ToastProvider";

const issueTypes = ["Invalid Grievance", "Duplicate Grievance", "Wrong Department", "Wrong Location", "Insufficient Information", "Citizen Clarification Required", "Requires Specialized Skill/Team", "Material/Equipment Required", "Manager Approval Required", "Safety Concern", "Outside Department Jurisdiction", "Unable to Resolve", "Access/Location Issue", "Other"];
const status = (g: Grievance) => (g.state ?? g.status ?? "").toUpperCase();
const date = (v?: string | null) => v ? new Date(v).toLocaleDateString() : "Not set";

export function ResolverWorkspace() {
  const { notify } = useToast();
  const [items, setItems] = useState<Grievance[]>([]); const [selected, setSelected] = useState<Grievance | null>(null); const [history, setHistory] = useState<unknown[]>([]); const [note, setNote] = useState(""); const [hold, setHold] = useState(""); const [resolution, setResolution] = useState(""); const [issueType, setIssueType] = useState(issueTypes[0]); const [issue, setIssue] = useState(""); const [suggestion, setSuggestion] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const next = await listGrievances() as Grievance[]; setItems(next); setSelected((old) => old ? next.find((g) => g.id === old.id) ?? null : next[0] ?? null); }, []);
  // Loading server state on mount is intentional; the resolver queue is the source of truth.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load().catch((e) => setMessage(e instanceof Error ? e.message : "Could not load tasks")); }, [load]);
  useEffect(() => { if (selected) void getGrievanceHistory(selected.id).then(setHistory).catch(() => setHistory([])); }, [selected]);
  const metrics = useMemo(() => { const completed = items.filter((g) => ["RESOLUTION_SUBMITTED", "RESOLVED", "CLOSED"].includes(status(g))).length; const pending = items.filter((g) => ["ASSIGNED", "ACCEPTED", "PENDING_ASSIGNMENT"].includes(status(g))).length; const inProgress = items.filter((g) => status(g) === "IN_PROGRESS").length; const onHold = items.filter((g) => status(g) === "BLOCKED").length; const overdue = items.filter((g) => g.dueDate && new Date(g.dueDate) < new Date() && !["RESOLVED", "CLOSED"].includes(status(g))).length; return { total: items.length, completed, pending, inProgress, onHold, overdue, rate: items.length ? Math.round(completed / items.length * 100) : 0 }; }, [items]);
  async function act(fn: () => Promise<unknown>) { setBusy(true); setMessage(""); try { await fn(); await load(); setMessage("Saved successfully."); notify("Update saved", "Your grievance task has been updated."); } catch (e) { const text = e instanceof Error ? e.message : "Action failed"; setMessage(text); notify("Action failed", text, "error"); } finally { setBusy(false); } }
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-ink-950">My work dashboard</h1><p className="mt-1 text-sm text-ink-600">Review assignments, record progress, and raise issues early so managers can unblock your work.</p></div>
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Total assigned", metrics.total], ["Pending", metrics.pending], ["In progress", metrics.inProgress], ["Completed", metrics.completed], ["On hold", metrics.onHold], ["Overdue", metrics.overdue]].map(([label, value]) => <Card key={String(label)}><CardBody><p className="text-xs font-semibold uppercase tracking-wide text-ink-500">{label}</p><p className="mt-2 text-2xl font-bold text-ink-950">{value}</p></CardBody></Card>)}</div>
    <Card><CardBody><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Overall progress</p><p className="mt-1 text-xs text-ink-500">{metrics.completed} of {metrics.total} assignments submitted for review</p></div><strong className="text-xl text-primary-700">{metrics.rate}%</strong></div><div className="mt-3 h-2 rounded-full bg-ink-100"><div className="h-2 rounded-full bg-primary-600" style={{ width: `${metrics.rate}%` }} /></div></CardBody></Card>
    <div className="grid gap-6 lg:grid-cols-[350px_1fr]"><Card><CardHeader title="My tasks" subtitle={`${items.length} assigned grievance${items.length === 1 ? "" : "s"}`} /><CardBody className="space-y-2">{items.length === 0 && <p className="text-sm text-ink-500">No tasks are assigned to you yet.</p>}{items.map((g) => <button key={g.id} onClick={() => setSelected(g)} className={`w-full rounded-lg border p-3 text-left ${selected?.id === g.id ? "border-primary-600 bg-primary-50" : "border-ink-200 hover:bg-ink-50"}`}><div className="flex justify-between gap-2"><span className="font-mono text-xs">{g.id}</span><PriorityBadge priority={g.priority} /></div><p className="mt-1 text-sm font-semibold">{g.title}</p><div className="mt-2 flex justify-between gap-2"><StatusBadge status={g.state ?? g.status} /><span className="text-xs text-ink-500">Due {date(g.dueDate)}</span></div></button>)}</CardBody></Card>
      <Card><CardBody className="space-y-6">{!selected ? <p className="text-sm text-ink-500">Select a task to view its details.</p> : <><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs">{selected.id}</span><StatusBadge status={selected.state ?? selected.status} /><PriorityBadge priority={selected.priority} /></div><h2 className="mt-3 text-xl font-bold text-ink-950">{selected.title}</h2><p className="mt-2 text-sm leading-6 text-ink-700">{selected.description}</p><p className="mt-3 text-xs text-ink-500">Department: <strong>{selected.departmentId ?? selected.category}</strong> · Submitted {date(selected.createdAt)} · Due {date(selected.dueDate)}</p>{selected.latitude != null && selected.longitude != null && <a className="mt-1 block text-xs text-primary-700 underline" href={`https://www.openstreetmap.org/?mlat=${selected.latitude}&mlon=${selected.longitude}`} target="_blank" rel="noreferrer">Open task location</a>}{selected.imageUrl && <img src={selected.imageUrl} alt="Citizen evidence" className="mt-4 max-h-56 rounded-lg object-cover" />}</div>
        <div className="flex flex-wrap gap-2">{status(selected) === "ASSIGNED" && <Button disabled={busy} onClick={() => void act(() => acceptAssignment(selected.id))}>Accept assignment</Button>}{["ASSIGNED", "ACCEPTED", "BLOCKED"].includes(status(selected)) && <Button disabled={busy} onClick={() => void act(() => transitionGrievanceState(selected.id, { to_state: "IN_PROGRESS", reason: "Worker started work" }))}>Start work</Button>}</div>
        <Field label="Hold reason" hint="Required before placing work on hold"><Input value={hold} onChange={(e) => setHold(e.target.value)} placeholder="Awaiting materials, access, approval…" /></Field><Button variant="outline" disabled={busy || !hold.trim() || !["ASSIGNED", "ACCEPTED", "IN_PROGRESS"].includes(status(selected))} onClick={() => void act(() => transitionGrievanceState(selected.id, { to_state: "BLOCKED", reason: hold.trim() }))}>Place on hold</Button>
        <div className="border-t border-ink-100 pt-5"><h3 className="text-sm font-bold">Daily work update</h3><div className="mt-3 space-y-3"><Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Work performed, current situation, materials needed, and next action" rows={4} /><Button disabled={busy || !note.trim()} onClick={() => void act(async () => { await addProgressUpdate(selected.id, { bodyInternal: note.trim(), bodyCustomer: note.trim(), visibility: "customer", kind: "daily_update", workCompleted: note.trim() }); setNote(""); })}>Post update</Button></div></div>
        <div className="border-t border-ink-100 pt-5"><h3 className="text-sm font-bold">Raise issue / escalate to manager</h3><div className="mt-3 space-y-3"><Select value={issueType} onChange={(e) => setIssueType(e.target.value)}>{issueTypes.map((type) => <option key={type}>{type}</option>)}</Select><Textarea value={issue} onChange={(e) => setIssue(e.target.value)} placeholder="Explain what is preventing completion" /><Input value={suggestion} onChange={(e) => setSuggestion(e.target.value)} placeholder="Suggested action (optional)" /><Button variant="outline" disabled={busy || !issue.trim()} onClick={() => void act(async () => { await escalateGrievance(selected.id, { issueType, reason: issue.trim(), description: issue.trim(), suggestedAction: suggestion.trim() || undefined }); setIssue(""); setSuggestion(""); })}>Raise ticket</Button></div></div>
        <div className="border-t border-ink-100 pt-5"><h3 className="text-sm font-bold">Complete work for manager review</h3><div className="mt-3 space-y-3"><Textarea value={resolution} onChange={(e) => setResolution(e.target.value)} placeholder="Resolution remarks and work performed" rows={4} /><Button disabled={busy || !resolution.trim()} onClick={() => void act(async () => { await submitResolution(selected.id, resolution.trim()); setResolution(""); })}>Submit completion</Button></div></div>{message && <p className="text-sm text-primary-700">{message}</p>}
        <div className="border-t border-ink-100 pt-5"><h3 className="text-sm font-bold">Activity timeline</h3><div className="mt-3 space-y-2">{history.length === 0 ? <p className="text-xs text-ink-500">No activity recorded yet.</p> : history.map((entry, i) => { const e = entry as Record<string, unknown>; return <div key={i} className="rounded-lg bg-ink-50 p-3 text-xs"><strong>{String(e.kind ?? "State update")}</strong><span className="ml-3 text-ink-500">{date(String(e.at ?? e.createdAt ?? ""))}</span><p className="mt-1 text-ink-700">{String(e.bodyInternal ?? e.bodyCustomer ?? e.reason ?? e.to ?? "Activity recorded")}</p></div>; })}</div></div></>}</CardBody></Card></div></div>;
}
